# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb357c5e360904765b9b5e469d68ef4424f05e6466dccb058087cca4eaf00cf5775c27ab67d2ce7bab3f94c4d103922763b4731656eddae06bbb72240445b1eb

test:
  secret_key_base: 64ca76e184e2740fe41d9dc13bf39ea779b7b2ae7575d20b0da56d41de8b46819ec0a24634575bdbd29d9d9f5ff5c5cb899dedfb48547e8d77e8adbed83ec630

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
